/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./web/public/**/*.{html,js}",
  ],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        surface: "#090D16",
        "surface-container-low": "#0A0F1D",
        "surface-container": "#0F172A",
        "surface-container-high": "#162038",
        "surface-variant": "#1E293B",
        primary: "#3B82F6",
        "primary-container": "#1D4ED8",
        "on-primary": "#FFFFFF",
        "on-surface": "#F8FAFC",
        "on-surface-variant": "#94A3B8",
        "outline-variant": "#334155",
        accent: "#6366F1",
        crimson: "#EF4444",
        amber: "#F59E0B",
        emerald: "#10B981",
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        sans: ['Inter', '"Plus Jakarta Sans"', 'system-ui', '-apple-system', 'sans-serif'],
        body: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
      },
      boxShadow: {
        'glow-primary': '0 0 25px -5px rgba(59, 130, 246, 0.3)',
        'glow-crimson': '0 0 30px -5px rgba(239, 68, 68, 0.3)',
        'glow-emerald': '0 0 25px -5px rgba(16, 185, 129, 0.3)',
        'glow-accent': '0 0 25px -5px rgba(99, 102, 241, 0.3)',
      },
    },
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        dark: {
          ...require("daisyui/src/theming/themes")["dark"],
          primary: "#3B82F6",
          "primary-content": "#FFFFFF",
          secondary: "#6366F1",
          accent: "#38BDF8",
          neutral: "#1E293B",
          "base-100": "#0F172A",
          "base-200": "#0A0F1D",
          "base-300": "#162038",
          "base-content": "#F8FAFC",
          info: "#38BDF8",
          success: "#10B981",
          warning: "#F59E0B",
          error: "#EF4444",
        },
        light: {
          ...require("daisyui/src/theming/themes")["light"],
          primary: "#2563EB",
          "primary-content": "#FFFFFF",
          secondary: "#4F46E5",
          accent: "#0284C7",
          neutral: "#1E293B",
          "base-100": "#FFFFFF",
          "base-200": "#F8FAFC",
          "base-300": "#E2E8F0",
          "base-content": "#0F172A",
          info: "#0284C7",
          success: "#059669",
          warning: "#D97706",
          error: "#DC2626",
        },
      },
    ],
    defaultTheme: "dark",
  },
}
