import {createClient} from '@sanity/client'
import * as dotenv from 'dotenv'
import * as path from 'path'

dotenv.config({path: path.resolve(process.cwd(), '.env')})

const projectId = process.env.SANITY_PROJECT_ID
const dataset = process.env.SANITY_DATASET || 'production'
const token = process.env.SANITY_PROJECT_TOKEN

if (!projectId || !token) {
  console.error('Missing SANITY_PROJECT_ID or SANITY_PROJECT_TOKEN in .env')
  process.exit(1)
}

const client = createClient({
  projectId,
  dataset,
  token,
  apiVersion: '2024-01-01',
  useCdn: false,
})

export const verifiedSchemes = [
  {
    _id: 'scheme-goa-home-nursing',
    _type: 'scholarshipScheme',
    title: 'Directorate of Social Welfare Goa - Scholarship for Home Nursing Courses',
    slug: {current: 'goa-home-nursing-scholarship'},
    authority: 'Directorate of Social Welfare, Government of Goa',
    category: 'state',
    officialDocumentUrl: 'https://socialwelfare.goa.gov.in/wp-content/uploads/2025/04/Scheme-of-Scholarship-to-students-pursuing-home-nursing-Courses.pdf',
    documentTitle: 'Notification 13-1-84-SWD/Part/2025 - Scheme of Scholarship to Students Pursuing Home Nursing Courses',
    summary: 'State financial stipend scheme for Goan resident students enrolled in recognized home nursing training institutes.',
    benefits: 'Monthly stipend of Rs. 2,000/- for pursuing home nursing training.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'A scholarship holder under this scheme shall not avail any other scholarship/stipend for pursuing the same course.',
      clauseReference: 'Clause 7(b), Conditions of Award',
      consequenceOfViolation: 'Immediate termination of scholarship and forfeiture of eligibility under state welfare schemes.',
      allowedExceptions: 'None. Absolute prohibition on holding concurrent scholarships or stipends for the same course.',
    },
  },
  {
    _id: 'scheme-samsung-star-scholar',
    _type: 'scholarshipScheme',
    title: 'Samsung Star Scholar CSR Program',
    slug: {current: 'samsung-star-scholar'},
    authority: 'Samsung India Electronics Pvt. Ltd. (CSR Division)',
    category: 'corporate',
    officialDocumentUrl: 'https://images.samsung.com/is/content/samsung/assets/in/microsite/sapne-hue-bade/stories/StarScholarRuleBook.pdf',
    documentTitle: 'Samsung Star Scholar Program - Rules and Regulations Rulebook',
    summary: 'Corporate CSR merit scholarship supporting meritorious students from Navodaya Vidyalayas pursuing B.Tech/Dual Degree at IITs and NITs.',
    benefits: 'Financial support of up to INR 2,00,000/- per academic year covering tuition, hostel, and mess expenses.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'The student shall not avail any other financial assistance or scholarship from any Institute, Government or Non-Government source during the tenure of the scholarship.',
      clauseReference: 'Rulebook Section 4.3 (Disqualification & Forfeiture)',
      consequenceOfViolation: 'Immediate revocation of scholarship, debarment from Samsung CSR initiatives, and forfeiture of all unpaid tranches.',
      allowedExceptions: 'Strict zero-tolerance clause; no concurrent financial assistance permitted from any institute, government, or private body.',
    },
  },
  {
    _id: 'scheme-central-post-matric-sc-st-obc',
    _type: 'scholarshipScheme',
    title: 'Central Sector Post-Matric Scholarship for SC/ST/OBC Students',
    slug: {current: 'central-post-matric-sc-st-obc'},
    authority: 'Ministry of Social Justice & Empowerment, Government of India',
    category: 'central',
    officialDocumentUrl: 'https://www.myscheme.gov.in/hi/schemes/presm',
    documentTitle: 'Centrally Sponsored Post Matric Scholarship Scheme Guidelines (NSP Routed)',
    summary: 'Pan-India post-matric scheme enabling marginalized students to pursue higher education with full fee support.',
    benefits: 'Full non-refundable compulsory course fee reimbursement plus monthly maintenance allowance.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'The student must not be availing any other scholarship by the govt. If found receiving another government scholarship simultaneously, the scholarship will be cancelled immediately and the entire amount disbursed will be recovered.',
      clauseReference: 'Rule 5.1(iv) & Clause 9 (Recovery & Cancellation)',
      consequenceOfViolation: 'Immediate cancellation of award and mandatory statutory recovery/clawback of all disbursed funds.',
      allowedExceptions: 'No concurrent government scholarships permitted. Free-ship cards must be reconciled through NSP.',
    },
  },
  {
    _id: 'scheme-pm-yasasvi-pre-matric',
    _type: 'scholarshipScheme',
    title: 'PM YASASVI Pre-Matric Scholarship Scheme for OBC, EBC & DNT Students',
    slug: {current: 'pm-yasasvi-pre-matric'},
    authority: 'Ministry of Social Justice & Empowerment, Government of India',
    category: 'central',
    officialDocumentUrl: 'https://www.myscheme.gov.in/hi/schemes/pmyasasvipmsobcebcdnts',
    documentTitle: 'PM-YASASVI Scheme Guidelines, Department of Social Justice and Empowerment',
    summary: 'Pre-matric education assistance for students in classes 9 and 10 from marginalized communities.',
    benefits: 'Academic allowance of Rs. 4,000/- per annum.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'A scholarship holder under this scheme will not hold any other educational scholarship for the same stage of education. If awarded any other educational scholarship, the student can avail of either of the two scholarships as per his/her choice.',
      clauseReference: 'Clause 8 (Conditions of Eligibility)',
      consequenceOfViolation: 'Disqualification if both are accepted; student must officially surrender one scheme.',
      allowedExceptions: 'Formal choice allowed: student may choose to retain either scholarship by surrendering the other in writing.',
    },
  },
  {
    _id: 'scheme-iit-guwahati-mcm',
    _type: 'scholarshipScheme',
    title: 'IIT Guwahati Merit-cum-Means Institute Scholarship',
    slug: {current: 'iit-guwahati-mcm-scholarship'},
    authority: 'Indian Institute of Technology Guwahati (Senate)',
    category: 'institute',
    officialDocumentUrl: 'https://www.iitg.ac.in/fresherportal/ScholarshipOrdinance.pdf',
    documentTitle: 'IIT Guwahati Ordinances on Scholarships, Stipends, Medals and Prizes',
    summary: 'Merit-cum-means scholarship for undergraduate students admitted to B.Tech/B.Des programs at IIT Guwahati.',
    benefits: 'Full tuition fee waiver and monthly stipend allowance of Rs. 1,000/-.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'A student shall not ordinarily receive any other scholarship, stipend, financial assistance, freeship or remuneration from any other source except with the prior permission of the competent authority.',
      clauseReference: 'Ordinance Section 2, Rule 6(a)',
      consequenceOfViolation: 'Cancellation of MCM award and disciplinary review by Senate unless prior permission was secured.',
      allowedExceptions: 'Permitted ONLY with prior written permission of the competent authority (Dean of Students Affairs / Senate).',
    },
  },
  {
    _id: 'scheme-ftii-scholarship',
    _type: 'scholarshipScheme',
    title: 'Film and Television Institute of India (FTII) Student Scholarship Scheme',
    slug: {current: 'ftii-scholarship-scheme'},
    authority: 'Film and Television Institute of India, Ministry of I&B',
    category: 'institute',
    officialDocumentUrl: 'https://ftii.ac.in/api/serve/2026/06/19/03._Scholarship_-_Rules_and_Regulation_1.pdf',
    documentTitle: 'FTII Scholarship Rules and Regulation Document No. 03',
    summary: 'Institute scholarship and freeship support for film and television diploma students.',
    benefits: 'Partial to full tuition fee waiver plus academic project grant.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'A student shall not receive more than one scholarship/assistantship/freeship except for scholarships sponsored by Centre or State Government. In case a student is offered another scholarship, they must make a formal written choice within 15 days.',
      clauseReference: 'Regulation 4.2 & Procedure 5',
      consequenceOfViolation: 'Automated forfeiture of the institute scholarship upon failure to exercise written option within 15 days.',
      allowedExceptions: 'Explicitly permits concurrent Centre or State government scholarships (stacking allowed with government schemes).',
    },
  },
  {
    _id: 'scheme-reliance-foundation-ug',
    _type: 'scholarshipScheme',
    title: 'Reliance Foundation Undergraduate Scholarship',
    slug: {current: 'reliance-foundation-undergraduate'},
    authority: 'Reliance Foundation (CSR Initiative)',
    category: 'corporate',
    officialDocumentUrl: 'https://www.reliancefoundation.org/scholarships',
    documentTitle: 'Reliance Foundation Undergraduate Scholarships Program Guidelines & Regulations',
    summary: 'Merit-cum-means scholarship for undergraduate students pursuing first-year degree programs across all disciplines in India.',
    benefits: 'Up to INR 2,00,000/- over the duration of the degree program.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'Scholars may not hold any other corporate or private philanthropic scholarship. Government scholarships or college fee waivers are permitted provided the total combined financial aid does not exceed verified institutional fees.',
      clauseReference: 'Section 6 (Concurrent Financial Aid & Compliance)',
      consequenceOfViolation: 'Immediate termination of scholarship and cancellation of subsequent tranche disbursements.',
      allowedExceptions: 'Permits government merit scholarships or state tuition fee-waivers up to actual college fee amount.',
    },
  },
  {
    _id: 'scheme-tata-trusts-medical',
    _type: 'scholarshipScheme',
    title: 'Tata Trusts Medical and Healthcare Studies Grant',
    slug: {current: 'tata-trusts-medical-grant'},
    authority: 'Tata Trusts (Sir Ratan Tata Trust & Allied Trusts)',
    category: 'corporate',
    officialDocumentUrl: 'https://www.tatatrusts.org/our-work/individual-grants-programme/education-grants',
    documentTitle: 'Tata Trusts Individual Grants Programme - Higher Education Regulations',
    summary: 'Need-based educational grant for students pursuing undergraduate and postgraduate medical (MBBS/BDS) studies in India.',
    benefits: 'Partial to full tuition fee grant directly disbursed to medical college.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'Students receiving full tuition fee reimbursement from any other trust, foundation, or philanthropic body are ineligible. Any concurrent external assistance towards tuition must be declared; failure to disclose triggers full grant clawback.',
      clauseReference: 'Clause 3.4 (Disclosure of External Aid)',
      consequenceOfViolation: 'Revocation of grant and debarment of student and institution from future Tata Trusts initiatives.',
      allowedExceptions: 'Government travel or book allowances are permitted; duplicate tuition grants are strictly barred.',
    },
  },
  {
    _id: 'scheme-aditya-birla-scholarship',
    _type: 'scholarshipScheme',
    title: 'Aditya Birla Group Scholarship',
    slug: {current: 'aditya-birla-scholarship'},
    authority: 'Aditya Birla Management Corporation Pvt. Ltd.',
    category: 'corporate',
    officialDocumentUrl: 'https://www.adityabirlascholars.net/about/Scholarship.aspx',
    documentTitle: 'Aditya Birla Scholarship Scheme Guidelines for Premier IIT, IIM, and Law Institutes',
    summary: 'Prestige leadership scholarship covering top-ranking entrants at premier Indian institutes including IITs, BITS, IIMs, and XLRI.',
    benefits: 'Annual scholarship amount of INR 1,80,000/- for engineering and INR 3,00,000/- for management.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'An Aditya Birla Scholar shall not hold any other corporate scholarship or commercial stipend. Holding an institute or government fee concession is permissible with prior notification to the Advisory Board.',
      clauseReference: 'Terms of Acceptance, Clause 8',
      consequenceOfViolation: 'Revocation of scholar status, loss of citation, and cessation of future financial grants.',
      allowedExceptions: 'Institute merit-cum-means waivers and national government scholarships are allowed upon formal notice.',
    },
  },
  {
    _id: 'scheme-ongc-sc-st',
    _type: 'scholarshipScheme',
    title: 'ONGC Foundation Scholarship for SC/ST Students',
    slug: {current: 'ongc-scholarship-sc-st'},
    authority: 'Oil and Natural Gas Corporation (ONGC) Foundation',
    category: 'corporate',
    officialDocumentUrl: 'https://ongcscholar.org/rules_regulations',
    documentTitle: 'ONGC Foundation Merit-cum-Means Scholarship Guidelines for SC/ST Category',
    summary: 'Financial support for meritorious SC/ST students enrolled in Engineering, MBBS, MBA, or Master in Geophysics/Geology.',
    benefits: 'Annual stipend of INR 48,000/- (INR 4,000/- per month).',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'The beneficiary should not be in receipt of any other scholarship or financial assistance from Central/State Government, public sector undertaking, or any other institution during the tenure of this scholarship.',
      clauseReference: 'Rule 4(e) (Eligibility Criteria & Undertaking)',
      consequenceOfViolation: 'Immediate termination of award and recovery of entire scholarship amount disbursed.',
      allowedExceptions: 'None. Absolute prohibition on holding any concurrent government or PSU assistance.',
    },
  },
  {
    _id: 'scheme-aicte-pragati',
    _type: 'scholarshipScheme',
    title: 'AICTE Pragati Scholarship Scheme for Girl Students',
    slug: {current: 'aicte-pragati-scholarship'},
    authority: 'All India Council for Technical Education (Ministry of Education)',
    category: 'central',
    officialDocumentUrl: 'https://www.aicte-india.org/schemes/students-development-schemes/Pragati',
    documentTitle: 'AICTE Pragati Scheme for Girls in Technical Degree and Diploma Programmes',
    summary: 'Government scheme providing advancement grants to girl students admitted to AICTE approved technical institutions.',
    benefits: 'INR 50,000/- per annum for every year of study towards college fees, computer purchase, and books.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'The candidate shall not be availing of any other scholarship scheme from Central/State Government or any other agency for the same course of study. Receipt of duplicate financial aid leads to automated PFMS portal rejection.',
      clauseReference: 'Scheme Guidelines Section 3.2 (Exclusion Covenants)',
      consequenceOfViolation: 'Cancellation of Pragati scholarship and automated de-registration on National Scholarship Portal.',
      allowedExceptions: 'State government transport or uniform concessions only; no direct cash or tuition scholarships permitted.',
    },
  },
  {
    _id: 'scheme-aicte-saksham',
    _type: 'scholarshipScheme',
    title: 'AICTE Saksham Scholarship Scheme for Specially Abled Students',
    slug: {current: 'aicte-saksham-scholarship'},
    authority: 'All India Council for Technical Education (Ministry of Education)',
    category: 'central',
    officialDocumentUrl: 'https://www.aicte-india.org/schemes/students-development-schemes/Saksham',
    documentTitle: 'AICTE Saksham Scheme for Specially Abled Degree/Diploma Technical Students',
    summary: 'Empowerment scholarship for students with disability of not less than 40% pursuing technical higher education.',
    benefits: 'INR 50,000/- per annum for tuition fees, assistive devices, and educational software.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'The scholar must not receive any duplicate financial assistance from other central government sources or public welfare funds for pursuing technical education.',
      clauseReference: 'Regulation 2.4 (Conditions of Sanction)',
      consequenceOfViolation: 'Revocation of scholarship and recovery via institutional audit proceedings.',
      allowedExceptions: 'Disability pension or welfare stipend from State Social Welfare department is permitted.',
    },
  },
  {
    _id: 'scheme-pmrf-fellowship',
    _type: 'scholarshipScheme',
    title: 'Prime Minister Research Fellowship (PMRF)',
    slug: {current: 'prime-ministers-research-fellowship'},
    authority: 'Ministry of Education, Government of India (National Coordinating Institute: IIT Madras)',
    category: 'central',
    officialDocumentUrl: 'https://www.pmrf.in/guidelines',
    documentTitle: 'PMRF Scheme Guidelines for Direct and Lateral Entry Doctoral Scholars',
    summary: 'Flagship national research fellowship for Ph.D. students in frontier science and technology at IITs, IISc, and IISERs.',
    benefits: 'Monthly fellowship of INR 70,000/- to INR 80,000/- plus annual contingency grant of INR 2,00,000/-.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'A PMRF fellow is strictly barred from availing any other fellowship, stipend, salary, or financial remuneration from any public or private funding agency during the fellowship tenure. Dual funding constitutes academic misconduct.',
      clauseReference: 'PMRF Governance Rules, Section 5.1 (Exclusivity Clause)',
      consequenceOfViolation: 'Immediate termination of PMRF status, debarment from institute research fellowships, and full recovery.',
      allowedExceptions: 'None. Total exclusivity mandated by Central Ministry.',
    },
  },
  {
    _id: 'scheme-inspire-she',
    _type: 'scholarshipScheme',
    title: 'INSPIRE Scholarship for Higher Education (SHE)',
    slug: {current: 'inspire-she-scholarship'},
    authority: 'Department of Science and Technology (DST), Government of India',
    category: 'central',
    officialDocumentUrl: 'https://online-inspire.gov.in/Guideline/SHE_Guidelines.pdf',
    documentTitle: 'Guidelines for Innovation in Science Pursuit for Inspired Research (INSPIRE) - SHE',
    summary: 'Scholarship scheme attracting brilliant young minds to basic and natural sciences at B.Sc./M.Sc. levels.',
    benefits: 'Annual scholarship of INR 80,000/- (INR 60,000/- scholarship + INR 20,000/- summer research mentorship).',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'Scholars cannot concurrently hold any other fellowship, scholarship, or freeship from DST, DBT, CSIR, UGC, or Central/State Governments. If selected for another award, the scholar must opt for one and surrender the other.',
      clauseReference: 'SHE Guidelines Clause 4.3 (Non-Stacking Regulation)',
      consequenceOfViolation: 'Cancellation of INSPIRE registration and permanent block on DST portal.',
      allowedExceptions: 'Written option to surrender within 30 days of dual award notification.',
    },
  },
  {
    _id: 'scheme-mahadbt-post-matric-obc',
    _type: 'scholarshipScheme',
    title: 'Maharashtra MahaDBT Post-Matric Scholarship for OBC Students',
    slug: {current: 'mahadbt-obc-post-matric'},
    authority: 'Department of Other Backward Bahujan Welfare, Government of Maharashtra',
    category: 'state',
    officialDocumentUrl: 'https://mahadbt.maharashtra.gov.in/SchemeData/SchemeData?str=E9DDFA3703664B13B1F8',
    documentTitle: 'Post Matric Scholarship to OBC Students - MahaDBT Portal Rulebook',
    summary: 'State educational support for OBC students enrolled in post-matric courses recognized by the government.',
    benefits: '50% to 100% tuition and exam fee reimbursement plus monthly maintenance allowance.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'Applicants holding dual state freeships or scholarships will face cancellation of both awards and statutory demand notices under the Maharashtra Land Revenue Code for recovery of disbursed amounts.',
      clauseReference: 'Rule 8 (Recovery & Disqualification)',
      consequenceOfViolation: 'Cancellation of award, criminal prosecution under IPC for false declaration, and land revenue recovery.',
      allowedExceptions: 'None. Only one state or central welfare freeship allowed at any given time.',
    },
  },
  {
    _id: 'scheme-karnataka-epass-vidyasiri',
    _type: 'scholarshipScheme',
    title: 'Karnataka Vidyasiri (Food & Accommodation) Post-Matric Scheme',
    slug: {current: 'karnataka-vidyasiri-epass'},
    authority: 'Backward Classes Welfare Department, Government of Karnataka',
    category: 'state',
    officialDocumentUrl: 'https://karepass.cgg.gov.in/docs/vidyasiri_guidelines.pdf',
    documentTitle: 'Vidyasiri Food & Accommodation Scheme for Post-Matric Non-Hosteller Students',
    summary: 'Stipendiary scheme for rural backward classes students studying in post-matric courses who do not get government hostel seats.',
    benefits: 'Monthly allowance of INR 1,500/- for 10 months (INR 15,000/- per academic year).',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'Students availing free hostel admission, food allowance, or similar lodging stipends under other state/central welfare departments are disqualified from Vidyasiri stipends.',
      clauseReference: 'Eligibility Condition 3(c)',
      consequenceOfViolation: 'Immediate stoppage of monthly DBT credits and blacklisting on Karnataka e-PASS portal.',
      allowedExceptions: 'Tuition-only fee concessions from private colleges are permitted; room/food allowances cannot stack.',
    },
  },
  {
    _id: 'scheme-svmcm-west-bengal',
    _type: 'scholarshipScheme',
    title: 'West Bengal Swami Vivekananda Merit-cum-Means Scholarship (SVMCM)',
    slug: {current: 'west-bengal-svmcm'},
    authority: 'Higher Education Department, Government of West Bengal',
    category: 'state',
    officialDocumentUrl: 'https://svmcm.wbhed.gov.in/page/guidelines.php',
    documentTitle: 'Swami Vivekananda Merit-cum-Means Scholarship Scheme Guidelines (Version 4.0)',
    summary: 'Flagship West Bengal merit scholarship for meritorious students of economically vulnerable families pursuing higher education.',
    benefits: 'INR 1,000/- to INR 5,000/- per month depending on degree and postgraduate level.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'The student must not be receiving any other state government scholarship or stipend for the same course of study. A candidate cannot receive SVMCM and Kanyashree K3 simultaneously without deduction.',
      clauseReference: 'Section 4, Eligibility & Non-Duplication Clause',
      consequenceOfViolation: 'Cancellation of SVMCM sanction and refund of credited tranches via institutional treasury.',
      allowedExceptions: 'Kanyashree K3 awardees receive differential amount only, subject to formal reconciliation.',
    },
  },
  {
    _id: 'scheme-delhi-state-merit-sc-st',
    _type: 'scholarshipScheme',
    title: 'Delhi State Merit Scholarship for SC/ST/OBC/Minority Students',
    slug: {current: 'delhi-state-merit-scholarship'},
    authority: 'Department for the Welfare of SC/ST/OBC, Govt. of NCT of Delhi',
    category: 'state',
    officialDocumentUrl: 'https://scstwelfare.delhi.gov.in/schemes',
    documentTitle: 'Merit Scholarship to SC/ST/OBC/Minority Students Studying in Recognized Colleges',
    summary: 'State merit scholarship for students scoring 60%+ marks in qualifying examinations studying in Delhi institutions.',
    benefits: 'INR 10,000/- to INR 20,000/- per annum based on division.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'Beneficiaries cannot draw maintenance allowance or fee support simultaneously from Central NSP schemes and Delhi State Welfare schemes. Dual claim triggers automated PFMS account freeze.',
      clauseReference: 'Rule 6 (Dual Benefit Bar)',
      consequenceOfViolation: 'Rejection of application, PFMS bank account freeze, and notification to college principal.',
      allowedExceptions: 'Freeship book grants from college union funds up to INR 2,000/- are exempt.',
    },
  },
  {
    _id: 'scheme-tamil-nadu-post-matric',
    _type: 'scholarshipScheme',
    title: 'Tamil Nadu Post-Matric Scholarship Scheme for SC/ST Converts',
    slug: {current: 'tamil-nadu-post-matric-sc-st'},
    authority: 'Adi Dravidar and Tribal Welfare Department, Government of Tamil Nadu',
    category: 'state',
    officialDocumentUrl: 'https://adwelfare.tn.gov.in/postmatric_guidelines',
    documentTitle: 'Adi Dravidar and Tribal Welfare Post-Matric Scheme Operational Manual',
    summary: 'Comprehensive fee support and maintenance allowance for SC/ST and converted Christian students in Tamil Nadu colleges.',
    benefits: 'Full non-refundable compulsory fees and annual maintenance allowance.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'Holders of this scholarship cannot hold any other government scholarship or stipend unless specifically authorized by the Commissioner of Adi Dravidar Welfare.',
      clauseReference: 'Clause 9.1 (Prohibition of Concurrent Awards)',
      consequenceOfViolation: 'Recovery of disbursed amount and cancellation of subsequent academic year renewal.',
      allowedExceptions: 'Special prizes and sports medals awarded on one-time merit are exempt from the stacking bar.',
    },
  },
  {
    _id: 'scheme-up-post-matric-fee',
    _type: 'scholarshipScheme',
    title: 'Uttar Pradesh Post-Matric Scholarship & Fee Reimbursement Scheme',
    slug: {current: 'up-post-matric-scholarship'},
    authority: 'Social Welfare Department, Government of Uttar Pradesh',
    category: 'state',
    officialDocumentUrl: 'https://scholarship.up.gov.in/Rules_Regulations.aspx',
    documentTitle: 'UP Dashmottar Scholarship and Fee Reimbursement Operational Guidelines',
    summary: 'Financial support covering complete non-refundable fees and monthly stipends for UP domicile students.',
    benefits: 'Tuition fee reimbursement up to INR 50,000/- plus maintenance allowance.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'Dual registration or receipt of benefits from UP Scholarship portal and Central National Scholarship Portal (NSP) is strictly prohibited. It triggers instant FIR filing for financial fraud and land revenue recovery.',
      clauseReference: 'Rule 11 (Duplicate Benefit Prohibition & Penalties)',
      consequenceOfViolation: 'Permanent blacklist, FIR registration for fiscal fraud, and 100% recovery with statutory interest.',
      allowedExceptions: 'None. Absolute bar across state and national scholarship registries.',
    },
  },
  {
    _id: 'scheme-iit-bombay-mcm',
    _type: 'scholarshipScheme',
    title: 'IIT Bombay Institute Merit-cum-Means (MCM) Scholarship',
    slug: {current: 'iit-bombay-mcm-scholarship'},
    authority: 'Indian Institute of Technology Bombay (Senate Committee on Scholarships)',
    category: 'institute',
    officialDocumentUrl: 'https://www.iitb.ac.in/academic/scholarship.jsp',
    documentTitle: 'Rules and Regulations for Institute Merit-cum-Means Scholarship, IIT Bombay',
    summary: 'Merit-cum-means assistance awarded to up to 25% of sanctioned undergraduate intake at IIT Bombay.',
    benefits: 'Tuition fee waiver (INR 1,00,000/- per semester) plus INR 1,000/- monthly stipend.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'Awardees cannot receive any other private or government scholarship, stipend, or financial aid exceeding the tuition amount without prior sanction of Dean of Student Affairs. External aid must be adjusted against tuition waiver.',
      clauseReference: 'MCM Ordinance Regulation 5(b)',
      consequenceOfViolation: 'Reduction or cancellation of MCM award and retrospective clawback of tuition waiver.',
      allowedExceptions: 'Government scholarships covering living expenses only can be held with prior Dean clearance.',
    },
  },
  {
    _id: 'scheme-bits-pilani-mcn',
    _type: 'scholarshipScheme',
    title: 'BITS Pilani Merit-cum-Need (MCN) Scholarship',
    slug: {current: 'bits-pilani-mcn-scholarship'},
    authority: 'Birla Institute of Technology and Science, Pilani (Student Welfare Division)',
    category: 'institute',
    officialDocumentUrl: 'https://www.bits-pilani.ac.in/scholarships-fees',
    documentTitle: 'BITS Pilani Division of Student Welfare Policy Document on Institutional Aid',
    summary: 'Need-based tuition concession awarded to meritorious BITS Pilani students whose gross parental income is below specified ceilings.',
    benefits: '25%, 40%, or 80% tuition fee concession per semester.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'Students must disclose all external scholarships. If a student receives external financial assistance covering tuition, the BITS institutional concession will be reduced proportionally to ensure total aid does not exceed 100% tuition.',
      clauseReference: 'Policy Document Section 3 (External Aid Reconciliation)',
      consequenceOfViolation: 'Proportional recovery from student mess and hostel advance deposit account.',
      allowedExceptions: 'Permits partial stacking; external scholarships are subtracted from institutional concession.',
    },
  },
  {
    _id: 'scheme-national-overseas-sc',
    _type: 'scholarshipScheme',
    title: 'National Overseas Scholarship for SC/ST/De-notified Tribe Students',
    slug: {current: 'national-overseas-scholarship'},
    authority: 'Ministry of Social Justice & Empowerment, Government of India',
    category: 'central',
    officialDocumentUrl: 'https://nosmsje.gov.in/guidelines',
    documentTitle: 'National Overseas Scholarship Scheme Guidelines for Masters and Ph.D. Abroad',
    summary: 'Prestigious overseas fellowship funding full international tuition, living allowance, and travel for marginalized scholars abroad.',
    benefits: 'Full overseas tuition fees, annual maintenance allowance of USD 15,400/- (or GBP 9,900/-), visa and insurance.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'Scholars selected for NOS cannot draw fellowship or financial assistance from foreign governments, host university teaching assistantships, or Commonwealth bodies without explicit ministerial sanction.',
      clauseReference: 'Clause 7.2 (Undertaking and Employment Bar)',
      consequenceOfViolation: 'Revocation of scholarship, recall of student to India, and execution of parent surety bond.',
      allowedExceptions: 'University teaching assistantships up to 10 hours/week are permitted with prior embassy approval.',
    },
  },
  {
    _id: 'scheme-ishan-uday-ugc',
    _type: 'scholarshipScheme',
    title: 'Ishan Uday Special Scholarship Scheme for North Eastern Region',
    slug: {current: 'ishan-uday-ner-ugc'},
    authority: 'University Grants Commission (Ministry of Education)',
    category: 'central',
    officialDocumentUrl: 'https://www.ugc.gov.in/ner',
    documentTitle: 'UGC Ishan Uday Special Scholarship Scheme Guidelines for NER Students',
    summary: 'Special initiative providing 10,000 annual scholarships for North Eastern students enrolled in general degree and professional courses.',
    benefits: 'INR 5,400/- per month for general degree courses and INR 7,800/- per month for technical/medical courses.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'Awardees under Ishan Uday cannot hold any other scholarship from Central Government, State Government, or UGC during the award period. Multiple scholarships through NSP will result in cancellation.',
      clauseReference: 'Clause 6 (Conditions of Disqualification)',
      consequenceOfViolation: 'Cancellation of scholarship and mandatory refund of all credited tranches through NSP recovery mechanism.',
      allowedExceptions: 'College book bank facilities or library grants are exempt.',
    },
  },
  {
    _id: 'scheme-csir-ugc-jrf',
    _type: 'scholarshipScheme',
    title: 'CSIR-UGC Junior Research Fellowship (JRF)',
    slug: {current: 'csir-ugc-jrf-fellowship'},
    authority: 'Council of Scientific and Industrial Research (Human Resource Development Group)',
    category: 'central',
    officialDocumentUrl: 'https://csirhrdg.res.in/Home/Index/1/Default/2662/58',
    documentTitle: 'Terms & Conditions of CSIR Junior Research Fellowship (JRF-NET)',
    summary: 'Premier national competitive fellowship awarded to NET-qualified scholars pursuing doctoral research in science disciplines.',
    benefits: 'INR 37,000/- per month + House Rent Allowance (HRA) + annual contingency grant of INR 20,000/-.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'The fellow shall not accept any other appointment, paid or unpaid, or receive emoluments, salary, stipend, or fellowship from any other source during the fellowship tenure without prior CSIR approval.',
      clauseReference: 'Terms of Award Clause 4 (Exclusivity & Honorarium Bar)',
      consequenceOfViolation: 'Instant cancellation of JRF tenure and recovery of total fellowship with penal interest.',
      allowedExceptions: 'Occasional honorary lectures or guest tutorials not exceeding 4 hours/week are permitted.',
    },
  },
  {
    _id: 'scheme-kotak-kanya',
    _type: 'scholarshipScheme',
    title: 'Kotak Kanya Scholarship for Meritorious Girls',
    slug: {current: 'kotak-kanya-scholarship'},
    authority: 'Kotak Education Foundation (Kotak Mahindra Group CSR)',
    category: 'corporate',
    officialDocumentUrl: 'https://kotakeducation.org/kotak-kanya-scholarship',
    documentTitle: 'Kotak Kanya Scholarship Policy & Standard Operating Procedures',
    summary: 'CSR scholarship empowering meritorious female students from low-income families pursuing professional graduation courses.',
    benefits: 'Up to INR 1,50,000/- per year until completion of professional degree program.',
    stackingRule: {
      hasNonStackingRestriction: true,
      exactClauseText: 'Scholars cannot concurrently receive any other corporate CSR scholarship. State government fee concessions or reimbursement schemes are permitted provided the total assistance does not exceed actual educational expenditure.',
      clauseReference: 'Code of Compliance Section 2.3 (Corporate Aid Exclusions)',
      consequenceOfViolation: 'Withdrawal of future tranches and cancellation of mentorship membership.',
      allowedExceptions: 'Permits government tuition fee waivers and state welfare reimbursement cards.',
    },
  },
]

async function seed() {
  console.log(`Starting corpus seed into Sanity project: ${projectId}, dataset: ${dataset}...`)
  const tx = client.transaction()
  for (const scheme of verifiedSchemes) {
    tx.createOrReplace(scheme)
  }
  const result = await tx.commit()
  console.log(`Successfully seeded ${result.results.length} verified scholarship schemes!`)
  for (const s of verifiedSchemes) {
    console.log(` - [${s.category.toUpperCase()}] ${s.title}`)
    console.log(`   Quote: "${s.stackingRule.exactClauseText.slice(0, 75)}..."`)
  }
}

seed().catch((err) => {
  console.error('Failed to seed corpus:', err)
  process.exit(1)
})
